backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

locale: 'ja'
media_folder: ".vuepress/public/media" # Folder where user uploaded files should go

# This line should *not* be indented
publish_mode: editorial_workflow

collections:
  - name: "TechBlog"
    label: "01_技術情報"
    folder: "docs/01_技術情報"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "MannerBlog"
    label: "02_マナー情報"
    folder: "docs/02_マナー情報"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
